### ISSUE TITLE
Unquoting content-disposition looks bad

### ISSUE THREAD

**Issue by ayufan** [httpswift/swifter#107]
Please check how the (un-)escaper should work for content-dispositions: https://golang.org/src/mime/multipart/writer.go#L128

**Comment by glock45** [comment]
:+1:

**Comment by ayufan** [comment]
Is it resolved? :)

**Comment by glock45** [comment]
@ayufan don't know :) I navigated to https://golang.org/src/mime/multipart/writer.go#L128 and it presents encoding. Could you please paste a link for decoding ?
