### ISSUE TITLE
Failed to run demo

### ISSUE THREAD

**Issue by omerlh** [httpswift/swifter#109]
Hey there,
Swifter look really good :)
I've cloned the repo and tried to run the ios sample, using xcode 7.2.1 on ipad mini.
When I've first run it, it failed to found swifter framework. I've added it to the linked libraries (it wasn't there) and that issue fixed. Now the app crashed on this line (already tried to mark the framework module as optional or required, the same error occurred):
```swift 
 let server = demoServer(NSBundle.mainBundle().resourcePath!)
```
with the unhelpful exception dyld`dyld_fatal_error and the exception EXC_BREAKPOINT (code=1, autocode=0x1200b9088)

Probably I've did something wrong, as I am not ios expert, and I would like your help to fix it.

**Comment by satishmaha** [comment]
As of the latest commit 00e8a4b, the bridging header location is wrong. I've created a pull request for this: https://github.com/httpswift/swifter/pull/112

**Comment by satishmaha** [comment]
PR has been merged. Please GLV and see if it works

**Comment by omerlh** [comment]
OK, I will update.
