### ISSUE TITLE
Way to add custom handlers to requests?

### ISSUE THREAD

**Issue by dcvz** [httpswift/swifter#114]
Hello,

Is there any way I can set a handler for a path that contains a certain string? 

So I can set a wildcard such as this: `server.GET["*/api/:path"]` which will catch anything that has `/api/` one level in like `localhost:8080/layer/api/test.json` in it's path BUT it won't catch `localhost:8080/layer/deep/api/test.json` nor will it catch `localhost:8080/api/test.json`.

**Comment by dcvz** [comment]
looking more into the library seems like it would be possible by using the `server.GET[""]` however now I can't seem to find a way to set wildcards. For example: to intercept any request that has `/api/` in it's path.

**Comment by glock45** [comment]
Hi @dcvz 

You are right - it will work :) Example:

```
    server.GET["*/api/:path"] = { request in
        return .OK(.Html("Value for :path \(request.params[":path"])"))
    }
```
Results:
http://127.0.0.1:9080/layer/api/test.json -> Value for :path Optional("test.json")
http://127.0.0.1:9080/api/test.json -> 404
http://127.0.0.1:9080/layer/deep/api/test.json -> 404

Best,
dk

**Comment by dcvz** [comment]
Hey @glock45 my issue is that i'd like to be able to handle any `/api/` not just one layer in.. so for those example where it shows 404 not found, i'd like the handler to be able to catch them.

So what I'm proposing is to change the function of `*` to actually mean a wildcard and not just one layer of wildcard.

**Comment by glock45** [comment]
So I will need to introduce "**" operator to cover this case.

**Comment by dcvz** [comment]
Yes, I came to that conclusion as well. It would be best to introduce `**` as that follows typical directory structure wildcards.

**Comment by glock45** [comment]
@dcvz hi man. I've added a support for "**" ( https://github.com/httpswift/swifter/commit/77961679369c3489c32e224837711ef66518af15#diff-89fefdaa6dc1e7be0b467ca441ab25ebR107 ).

**Comment by dcvz** [comment]
Hey man this is great, thanks :)
