### ISSUE TITLE
How to return NSData from a response

### ISSUE THREAD

**Issue by marcoconti83** [httpswift/swifter#116]
When generating a response that is supposed to contain an image, e.g. with

```
server["/img"] = { 
      let data = dataForImgRequest($0)
      return .OK(...?...)
}
```

how can I return the raw bytes? 

It seems that I can choose between `.Text`, `.Json`, `.Html` and `.Custom`, but `.Custom` requires a closure that converts the object to a String. The image should not be serialised to a String but returned as-is. 

Is there a way to achieve this in Swifter?

**Comment by s-aska** [comment]
What about this? :dizzy:

```swift
let data = UIImagePNGRepresentation(image)!
let res = Array(UnsafeBufferPointer(start: UnsafePointer<UInt8>(data.bytes), count: data.length))
return HttpResponse.RAW(200, "OK", nil, { (writer: HttpResponseBodyWriter) in
    writer.write(res)
})
```

Thanks

**Comment by marcoconti83** [comment]
Thanks for the suggestion @s-aska 
I ended up with something very similar, but also passing the content type: 
```  
return .RAW(200, "OK", ["Content-Type": "image/png"], bodyWriteFunction)
```

It would be nice to have a more convenient method to do this, maybe a `.Data` on top of `.Text`, `.Json`, that can automatically set content-length and potentially content-type.

**Comment by glock45** [comment]
@marcoconti83 I've added _.Data_ enum case so now it's possible to return raw bytes array.

```
import Foundation
import Swifter

let server = HttpServer()

server["/data"] = { r in
    let data = [UInt8]("my test\n".utf8) 
    return .OK(.Data(data))
}

try? server.start(9080)

NSRunLoop.main().run()
```

best

**Comment by marcoconti83** [comment]
That's great, thank you @glock45!
