### ISSUE TITLE
'inout' must appear before the parameter name

### ISSUE THREAD

**Issue by AlexCatch** [httpswift/swifter#119]
I'm getting a lot of errors when building for OSX.

The majority are in 'Socket.swift' and are "Thrown expression type 'Socket Error' does not conform to 'Error Type'"

Any idea why these might be occurring?

I simply dropped the sources folder into my app and attempted to use the example provided.

**Comment by glock45** [comment]
hi @AlexCatch please see my comment here https://github.com/httpswift/swifter/issues/118#issuecomment-201756041
