### ISSUE TITLE
Slack channel is currently private

### ISSUE THREAD

**Issue by rofreg** [httpswift/swifter#120]
Hey there! I'm having an issue getting started with Swifter + Xcode 7.3, so I tried going to your Slack channel for help (as referenced in your README and in #118), but it appears to be invite-only. Can someone turn on email signup in the Slack channel settings?

**Comment by glock45** [comment]
@rofreg I've invited you to the channel.

**Comment by rofreg** [comment]
Thanks! I eventually figured out the issue on my own (Cocoapods got stuck in an odd state) – just wanted you to know that the Slack was private, in case that wasn't intentional.
