### ISSUE TITLE
'swift build -X': unable to import CSQLite

### ISSUE THREAD

**Issue by zmeyc** [httpswift/swifter#123]
I'm trying to generate a Xcode project using
swift build -X

When compiling this project I get an error:
>import CSQLite
No such module 'CSQLite'

'swift build' builds the library successfully from commandline.
I've checked that CSQLite is in Target dependencies in Build phases of Swifter.
Link Binary with Libraries contains libCSQLite.dylib.
Any ideas what could be missing?

**Comment by zmeyc** [comment]
Solved: manually added ".build/debug" to "Import Paths" in Build Settings. Might be worth adding to build instructions.

**Comment by zmeyc** [comment]
I realized that this links to the library built from console (by 'swift build'). Haven't yet found a way to import  CSQLite built by Xcode. :(

**Comment by glock45** [comment]
hi @zmeyc 

Adding "Sources/CSQLite/" to Swift Compiler - Search Paths - Import Paths should help. 

best

**Comment by zmeyc** [comment]
Thank you very much, it works.

**Comment by markie2902** [comment]
i tried that but still have the error

**Comment by zmeyc** [comment]
@markie2902 
I've tried:
```
git clone https://github.com/httpswift/swifter.git
swift package generate-xcodeproj
open Swifter.xcodeproj
```
and the project built succesfully without additional steps.
