### ISSUE TITLE
Optional not found handler

### ISSUE THREAD

**Issue by EvilClay** [httpswift/swifter#125]
Hi,
good job with the Swifter. I have a feature request

instead of returning ([:], { _ in HttpResponse.NotFound }) if no route is found, it would be use full to define a not found handler on HttpServer .. i.e.:

let server = HttpServer()
server.notFoundHandler = xxxx

also please make in HttpServer.swift the private let router = HttpRouter() -> internal let router ... so we can usefully override the dispatch method

**Comment by glock45** [comment]
@EvilClay I've added the notFoundHandler property. Let me know if it's ok for you.
