### ISSUE TITLE
Routing with optional params

### ISSUE THREAD

**Issue by trozware** [httpswift/swifter#126]
Not really an issue, just a question about routing.

I have a route like this:
`server["/doSomething/:outputName/:newSetting/:source"] = { req in`

but I also want to check for when the :source param is omitted and when both the :source and :newSetting params are omitted. (I supply default values for the processing that occurs).

Do I have to config three separate routes:
`server["/doSomething/:outputName/:newSetting/:source"] = { req in`
`server["/doSomething/:outputName/:newSetting"] = { req in`
`server["/doSomething/:outputName"] = { req in`

or is there a way to specify a param as optional but still assign a name to it?

**Comment by Vkt0r** [comment]
This would be covered in the documentation I'm working. But the short answer is you can verify it intercepting the request in your server and handling properly but by default, there is no support for optional parameters.
