### ISSUE TITLE
Request IP address (source IP) is broken

### ISSUE THREAD

**Issue by Laban1** [httpswift/swifter#129]
I am using the address property of HttpRequest to implement an ip whitelist for extra security.  It has been working great.  However, I just noticed that I had pinned my version to 1.0.7 in my Cartfile, so I changed this so that I can get later versions.  Unfortunately after doing this, my whitelist is now rejecting every host!

_It turns out that the address property now contains some IPv6 address instead of the IPv4 source address._  

Please fix this so that it is possible to get the source IP address again.

**Comment by jb431** [comment]
Same problem here!

**Comment by Laban1** [comment]
I just did some more testing and this property worked fine up till version 1.1.3 and broke with 1.1.4.

**Comment by glock45** [comment]
@Laban1 @jb431 you are right. I've released a new version with a fix - 1.2.0. 
IPv4 can be forced by the following flag: 

> try server.start(9080, forceIPv4: true)
