### ISSUE TITLE
Global pre-processing handler

### ISSUE THREAD

**Issue by Laban1** [httpswift/swifter#134]
We use your web service for an app where we have quite a few calls defined and for each an everyone of them, we have this logic to ensure the call is from an authorized source IP:

    if !WebServerUtil.AuthorizeCall(request) {
                return .Unauthorized
    }

Instead of duplicating this for every call, is there a way to define a "pre-processor" / handler that all web requests go through where we can either let the call through or handle it and return without letting it through?

Thanks again for creating this great little web server!

**Comment by glock45** [comment]
@Laban1 I've just added it to the stable branch ( https://github.com/httpswift/swifter/commit/ef0f703323ffbe6aa71643ce9a7abd0e95faba9c ). It will be public in the next release.

**Comment by Laban1** [comment]
Awesome!!  Thanks!
