### ISSUE TITLE
Pod install fails on tvos

### ISSUE THREAD

**Issue by lightbow** [httpswift/swifter#141]
When running pod install, I get:
[!] The platform of the target `Lightbow TV` (tvOS 9.0) is not compatible with `Swifter (1.2.0)`, which does not support `tvos`.

I'm fairly new to cocoapods, but see that you do indeed see s.tvos.deployment_target = '9.0' in your podspec, so I'm not sure whether it's on my end or not. Any ideas?

**Comment by glock45** [comment]
I think it's the problem on Swifter's side. "s.tvos.deployment_target = '9.0'" was added here (https://github.com/httpswift/swifter/pull/136/files) but there was no release since that. The next version (1.3.0) will cover this.

**Comment by page-fault-in-nonpaged-area** [comment]
Nope. tvOS still not found
