### ISSUE TITLE
Short names file and path are not properly served.

### ISSUE THREAD

**Issue by mbarnach** [httpswift/swifter#142]
Using OSX 10.11.5, short names files are not accessible.
To test it, use the demo server and replace the directory by a short one (like tmp), then try to download an existing file (with a name shorter than 7 characters + . 3 for extension).
The file cannot be found. Rename your file with more than 7 characters and it is found.
Looking at the code, it seems that withCString function usage from openFileFromMode are not working as expected: filename and mode have the same address.

**Comment by glock45** [comment]
@mbarnach 👍 it looks like you found potential vulnerability ! Swifter uses "withCString" in a wrong way. The pointer to C string array (needed for fopen) is valid only in the scope of closure function.
