### ISSUE TITLE
Request address empty in middleware 

### ISSUE THREAD

**Issue by Laban1** [httpswift/swifter#150]
Hello,

I am trying to use your new middleware method as a central place to verify that the caller is authorized to call the web server:

    server.middleware.append { request in
         if !WebServerUtil.AuthorizeCall(request) {
             return .Unauthorized
         }
         return nil
     }

However, the request.address property is empty in this call, so that does not work.

Please fix when you get a chance.

Thanks!

**Comment by glock45** [comment]
Hello !

It's becuase of this:https://github.com/httpswift/swifter/blob/stable/Sources/HttpServerIO.swift#L59

I will fix, add a test case for this and make a new release.

Best

**Comment by Laban1** [comment]
Great! As always, thanks for your quick response!!

**Comment by glock45** [comment]
Fixed here (https://github.com/httpswift/swifter/commit/f9a7fe1f105bb7ae9a1195114b24b6dac264aa52). I will close the ticket after release.
