### ISSUE TITLE
Websocket cause server crash on text message with payload of length 65536.

### ISSUE THREAD

**Issue by mbarnach** [httpswift/swifter#151]
Using a payload of size 65536 or higher, with websocket, cause a server crash here: https://github.com/httpswift/swifter/blob/stable/Sources/WebSockets.swift#L121

This can easily be tested with the following code in the swift interpreter:
`let len: UInt64 = 65536`
`print(UInt8(len >> 08))`

which raise: "Execution interrupted. Enter code to recover and continue.
Enter LLDB commands to investigate (type :help for assistance.)"

It is also possible to reproduce the crash with the Autobahn test suite, test number 1.1.7

**Comment by glock45** [comment]
@mbarnach thanks for this. I will have a look and provide the fix.

**Comment by glock45** [comment]
@mbarnach should be ok now (https://github.com/httpswift/swifter/commit/e6f2270040926b32f4e0f7b6b9eacfb310122ce4#diff-e151c339e14747169c44970649a2862fR102).

**Comment by mbarnach** [comment]
It works indeed! Thanks for the fast fix!
