### ISSUE TITLE
Invalid value of 'Upgrade' header: nil

### ISSUE THREAD

**Issue by ShashiBadhuk** [httpswift/swifter#165]
While running this code on device i am getting "Invalid value of 'Upgrade' header: nil" error message and it fails for handshaking,

**Comment by glock45** [comment]
@ShashiBadhuk It looks like an error which is returned by Swifter when somebody tries to open an websocekt endpoint in a browser. In that case the browser is not able to perform WebSockets handshake so Swifter rejects the request.

For testing WebSockets I use echo client from here (http://www.websocket.org/echo.html).

**Comment by glock45** [comment]
@ShashiBadhuk let me know if it's ok for you ?
