### ISSUE TITLE
shareFileFromDirectory Problem?

### ISSUE THREAD

**Issue by chrisyoyo** [httpswift/swifter#166]
Hello,
I think I have a problem, Bug or can't understand I don't know,

I have an test.html with a simple text formating -> <h1>TEST!</h1> on my desktop.
When I do : server["/desktop/:path"] = shareFilesFromDirectory("/Users/yovano_c/Desktop")
and i access to /desktop/test.html, it shows correctly. but if i remove the :path and i change my test.html to index.html, it show a really blank page, and sometimes when I try to access files it goes to the 404 (by default github) but i spell my file name correctly!... I don't know where's the problem.. thanks to you..

**Comment by glock45** [comment]
Hello :)

We don't support that yet in the master branch ( which is for swift 3.0 Preview X ~ XCode 8 Beta 3 ). We do have it in the last release of stable branch ( for Swift 2.x, thanks to https://github.com/httpswift/swifter/pull/124 ). What we have right now is a workaround and I have an other soultion for that case. 

The fix needs to by applied to HttpRouter class so **shareFilesFromDirectory** method can handle all the cases and offer index.html file for **/Users/yovano_c/Desktop**. 

Best

**Comment by chrisyoyo** [comment]
Oh thanks but I open 2 others tickets https://github.com/httpswift/swifter/issues/167 and https://github.com/httpswift/swifter/issues/168 if you can look at it please

**Comment by glock45** [comment]
Should be ok now for the master branch.
