### ISSUE TITLE
Stable / Master Branch

### ISSUE THREAD

**Issue by chrisyoyo** [httpswift/swifter#167]
I cannot understand your branch system:
Why the earlier version of the two is for xcode 8 and swift 3 and the other who has the recently push is on the most advanced version of Swifter but not for the swift 3.. I want to build a game server with a command line OSX app with swift 3, with a database on sqlite... I think swifter is cool for that but i need help with this 2 branch, thanks

**Comment by glock45** [comment]
Stable branch is more important than master. It's for the official releases of Swift from Apple. Tha last changes were mainly about the stability of WebSocket . Don't worry - all will be merged to master.

**Comment by chrisyoyo** [comment]
Oh okay but like I said on https://github.com/httpswift/swifter/issues/168 I can't use it with package.. i use swift 3...
