### ISSUE TITLE
Thread safety guideline?

### ISSUE THREAD

**Issue by xlc** [httpswift/swifter#172]
Is anything thread safe? Which thread does handler get called? How can I send web socket message from other thread safely?

**Comment by glock45** [comment]
`Is anything thread safe? Which thread does handler get called?`

On macOS we use GDC which I guess uses a thread pool and for Linux we spawn a new thread for every request (pthread_create) so It's not thread safe.

`How can I send web socket message from other thread safely?`

Every onText/onBinary callbacks offers a session object (https://github.com/httpswift/swifter/blob/master/Sources/Swifter/DemoServer.swift#L181)  which can be used by other threads. Just put a mutex around `session.write???`  (write methods do multiple send system calls and this is not thread safe).
