### ISSUE TITLE
Issue # 150  (Request address empty in middleware) still not resolved

### ISSUE THREAD

**Issue by Laban1** [httpswift/swifter#173]
Hello,

I just installed the latest version (1.2.6) and tried using the middleware functionality, but the request.address property is just an empty string here.

Please look into & fix when you get a chance.

Note: perhaps I should have re-opened issue # 150 instead of creating a new one, but I do not know how....

Thanks.

**Comment by glock45** [comment]
Hell @Laban1 . The fix is on the place but there was no new release since 1.2.6. I will go for 1.2.7.

**Comment by Laban1** [comment]
Ok, sounds good!

Thanks.
