### ISSUE TITLE
Stable branch should be master

### ISSUE THREAD

**Issue by lacyrhoades** [httpswift/swifter#174]
CocoaPods uses `master` as the default. Master crashes on serving an image file on iOS 9.3.3. If you change your project Podfile to say `:branch => "stable"` it works well. You can't change the default from the .podspec side of things. Perhaps `master` can be the stable branch, and then a second branch could exist for unstable development, i.e. branch `development` or similar.

**Comment by glock45** [comment]
Correct 👍 I took naming convention from https://github.com/apple/swift ( they have master for development ). Stable was my idea to maintain Swift 2.x. I wait for an offical release of Swift 3 and do the cleanup.
