### ISSUE TITLE
Noob question; urls.

### ISSUE THREAD

**Issue by kimaldis** [httpswift/swifter#175]
I've been assuming that the code below would allow me to use 'http://localhost/test' in a browser but the browser is unable to connect. I'm sure I'm making an obvious mistake but I can't find anything that tells me otherwise.

thanks

`server["/test"] = scopes {
            html {
                body {
                    h1 { inner = "test page" }
                }
            }
        }
`

**Comment by glock45** [comment]
Was it port number ?

**Comment by kimaldis** [comment]
Kind of. I was assuming port 80 but when I actually set the port number I was usgin http://localhost/test:8080. doh!

**Comment by chrisyoyo** [comment]
then use http://localhost:8080/test actually.

**Comment by kimaldis** [comment]
Yeah, I kind of worked that out.
