### ISSUE TITLE
ajax, encoded JSON

### ISSUE THREAD

**Issue by kimaldis** [httpswift/swifter#177]
I'm sending encoded JSON to a swifter server using jQuery ajax from a web page. This was all working fine until I had to send a string with an "=" in it and it all fell apart with the string being split at the = with the = being removed. I'm pretty sure I'm fundamentally misunderstanding how this should work but I can't see how else I might receive encoded JSON. Any help appreciated, my knowledge is a bit thin at this point.

server code: 

   `
            
         self.Server.GET["/lightroom"] = { r in   // HttpRequest object.
           // sent string gets split at =, into  r.queryParams[0].0, r.queryParams[0].1, etc
           print( "GET \(r.queryParams[0].0)" )
            print( "GET \(r.queryParams[0])" )

            let theDic = JSON().Decode( r.queryParams[0].0 )
            
            print( "GOT" )
            
            Globals.LightroomConnection.Write( theDic! )
            
            return HttpResponse.RAW(
                200,
                "OK",
                ["XXX-Custom-Header": "value"],
                { writer in try writer.write([UInt8]("Lightrem says ta".utf8)) }
            )
        }
   `

jQuery:

`
         
      $.ajax({
			url: "http://" + window.location.host + "/lightroom",
			data: JSON.stringify( {c: "aaa = bbb" ),  
			success: function( returnedJSON ) { 
				console.log( returnedJSON ); 
			},
			error: function(  jqXHR,  textStatus,  errorThrown ) {
				console.log( "Error: " + errorThrown )
				console.log( "Error Status: " + textStatus )
			}
		});`

**Comment by kimaldis** [comment]
Answering my own question, decoding r.path seems to be doing the job. Unless there's a better way?

**Comment by glock45** [comment]
I would switch to POST and pass the JSON as requests's body:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>lightroom</title>
  <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
</head>
<body>
  <script>
  $.ajax({
        url: "http://127.0.0.1:9080/lightroom",
        method: "POST",
        data: JSON.stringify({ key: "value" }),  
        success: function( returnedJSON ) { 
            console.log( returnedJSON ); 
        },
        error: function(  jqXHR,  textStatus,  errorThrown ) {
            console.log( "Error: " + errorThrown )
            console.log( "Error Status: " + textStatus )
        }
    });
  </script>
</body>
</html>
```

**Comment by kimaldis** [comment]
Of course. Thanks.
