### ISSUE TITLE
how to stream a video file in videoplayer as avplayer from webserver(http://123.134.134.....)

### ISSUE THREAD

**Issue by shindonghyeok** [httpswift/swifter#179]
i'd like to stream video file in player. video file exist in my own webserver. so what i want to do is i send a file url and get a file data and play file in video player... for example avplayer or anything is ok.. how can i do this??

**Comment by redwhitelabel** [comment]
As for now it's hard to accomplish, custom headers and new file serving is already ongoing, so it should be available easily in a couple of days.

**Comment by shindonghyeok** [comment]
so .. you mean that it is impossible?? right...?? or not?

**Comment by glock45** [comment]
@shindonghyeok it used to be supported by the older versions of Swifter but it was removed (00321c9). The reason of that is the implementation was loading a file into memory with every request. If you need that right now, please take what we have before.
