### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by nonew** [httpswift/swifter#180]
Hello, 
I have issue when run on real device iPhone, no issue on simulator. 
--------------------------------------------------------------------
dyld: Library not loaded: @rpath/Swifter.framework/Swifter
  Referenced from: /var/containers/Bundle/Application/5079DB58-6326-4838-A41A-E0C0A3B46B33/SwifterSampleiOS.app/SwifterSampleiOS
  Reason: image not found
(lldb) 
--------------------------------------------------------------------
Sorry for this silly question, I am newbie on iOS development

Thank you!

**Comment by glock45** [comment]
hello :)

Please add Swifter framework (iOS) to the embeded libraries:

![screen shot 2016-08-22 at 19 26 47](https://cloud.githubusercontent.com/assets/492449/17864470/85912890-689e-11e6-954c-81a5b56fb74d.png)

best
dk

**Comment by nonew** [comment]
Hello, glock
Yes, it is now working like charming.
BTW, I have another question, if I run the app from simulator, I can open server by type 127.0.0.1:9080 in browser, but if I run it from my iPhone, I cannot open the url from either iPhone or Mac browser. Do you know the possible reason?
Thank you!
