### ISSUE TITLE
Restrict to localhost

### ISSUE THREAD

**Issue by keepingitneil** [httpswift/swifter#191]
I'm using a server to broker communication between a WKWebView and the file system. I would like to restrict the server to only take requests from localhost for security purposes. Is there an easy way to accomplish this today?

**Comment by glock45** [comment]
HttpRequest object has `adddress` property so it can be achived by adding a middle-layer:

```
server.middleware.append { request in
        guard let address = request.address else {
            return .forbidden
        }
        guard ["127.0.0.1", "::1"].contains(address) else {
            return .forbidden
        }
        return nil // pass the request to upper layer.
    }
```

Best

**Comment by cezarbabin** [comment]
@glock45 for some reason the request address is never localhost. I'm not using proxy. No matter what device on the network I use, they're all the same IPv6 address, even the local machine.

Using iOS 10.3 to launch the server.
