### ISSUE TITLE
Is there a schedule to support xcode 8/swift 3?

### ISSUE THREAD

**Issue by pc9527** [httpswift/swifter#192]
swifter 1.2.6 won't compile in new iOS SDK. If support for new SDK is coming soon(kindly) I'll immediately start migrating my project to swift 3.0 syntax, for time being I'm sticking to legacy swift.

**Comment by git-no** [comment]
Swift 3 is the future and the present.
It would be great swifter with Swift 3 support.

**Comment by TristanWright** [comment]
Same question, or if this is going to stay on Swift 2.3 that would be good to know.

**Comment by Laban1** [comment]
Same question & need here.

**Comment by git-no** [comment]
FYI: Swifter migrated to Swift 3, XCode 8 is within the stable branch since yesterday available.

**Comment by glock45** [comment]
Yep. It's happening :)
