### ISSUE TITLE
Difference between master and stable branches?

### ISSUE THREAD

**Issue by TristanWright** [httpswift/swifter#193]

**Comment by glock45** [comment]
Hello,

**Stable** is for Swift 2.x.
**Master** is for Swift 3.x and expermients like: app layer (https://github.com/httpswift/swifter/blob/master/Sources/Swifter/App.swift), and pure TLS implementation (https://github.com/httpswift/swifter/tree/master/Sources/TLS).

Both did have their own life so I will need to merge a couple of bugfixes from master to stable. 

Right now there is no sense to keep both so master will die (I will keep app layer and TLS as side projects).
