### ISSUE TITLE
Many compile errors on Ubuntu 16.04 with swift 3.0 release

### ISSUE THREAD

**Issue by gery** [httpswift/swifter#194]
gery@gery-desktop:~/projects/swifter/swifter$ swift build
Compile Swift Module 'Swifter' (19 sources)
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:23:24: error: use of undeclared type 'NSData'
    func write(_ data: NSData) throws
                       ^~~~~~
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:24:24: error: use of undeclared type 'Data'
    func write(_ data: Data) throws
                       ^~~~
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:40:41: error: cannot convert return expression of type '(_) throws -> _' to return type '((HttpResponseBodyWriter) throws -> Void)?'
                    return (data.count, {
                                        ^
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:54:37: error: cannot convert return expression of type '(_) throws -> _' to return type '((HttpResponseBodyWriter) throws -> Void)?'
                return (data.count, {
                                    ^
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:60:37: error: cannot convert return expression of type '(_) throws -> _' to return type '((HttpResponseBodyWriter) throws -> Void)?'
                return (data.count, {
                                    ^
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:66:37: error: cannot convert return expression of type '(_) throws -> _' to return type '((HttpResponseBodyWriter) throws -> Void)?'
                return (data.count, {
                                    ^
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:72:33: error: cannot convert return expression of type '(_) throws -> _' to return type '((HttpResponseBodyWriter) throws -> Void)?'
            return (data.count, {
                                ^
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:23:24: error: use of undeclared type 'NSData'
    func write(_ data: NSData) throws
                       ^~~~~~
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:24:24: error: use of undeclared type 'Data'
    func write(_ data: Data) throws
                       ^~~~
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:23:24: error: use of undeclared type 'NSData'
    func write(_ data: NSData) throws
                       ^~~~~~
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:24:24: error: use of undeclared type 'Data'
    func write(_ data: Data) throws
                       ^~~~
/home/gery/projects/swifter/swifter/Sources/Socket+Server.swift:45:94: warning: missing '.self' for reference to metatype of type 'sockaddr_in'
                    bind(socketFileDescriptor, UnsafePointer<sockaddr>($0), socklen_t(sizeof(sockaddr_in)))
                                                                                             ^
                                                                                                        .self
/home/gery/projects/swifter/swifter/Sources/Socket+Server.swift:44:30: error: 'withUnsafePointer' has been renamed to 'withUnsafePointer(to:_:)'
                bindResult = withUnsafePointer(&addr) {
                             ^~~~~~~~~~~~~~~~~
                             withUnsafePointer to: 
Swift.withUnsafePointer:2:13: note: 'withUnsafePointer' has been explicitly marked unavailable here
public func withUnsafePointer<T, Result>(_ arg: inout T, _ body: (UnsafePointer<T>) throws -> Result) rethrows -> Result
            ^
/home/gery/projects/swifter/swifter/Sources/Socket+Server.swift:45:70: error: 'init' is unavailable: use 'withMemoryRebound(to:capacity:_)' to temporarily view memory as another layout-compatible type.
                    bind(socketFileDescriptor, UnsafePointer<sockaddr>($0), socklen_t(sizeof(sockaddr_in)))
                                                                     ^
Swift.UnsafePointer<Pointee>:9:12: note: 'init' has been explicitly marked unavailable here
    public init?<U>(_ from: UnsafePointer<U>?)
           ^
/home/gery/projects/swifter/swifter/Sources/Socket+Server.swift:45:87: error: 'sizeof' is unavailable: use MemoryLayout<T>.size instead.
                    bind(socketFileDescriptor, UnsafePointer<sockaddr>($0), socklen_t(sizeof(sockaddr_in)))
                                                                                      ^~~~~~~           ~
                                                                                      MemoryLayout<     >.size
/home/gery/projects/swifter/swifter/Sources/Socket+Server.swift:55:94: warning: missing '.self' for reference to metatype of type 'sockaddr_in6'
                    bind(socketFileDescriptor, UnsafePointer<sockaddr>($0), socklen_t(sizeof(sockaddr_in6)))
                                                                                             ^
                                                                                                         .self
/home/gery/projects/swifter/swifter/Sources/Socket+Server.swift:54:30: error: 'withUnsafePointer' has been renamed to 'withUnsafePointer(to:_:)'
                bindResult = withUnsafePointer(&addr) {
                             ^~~~~~~~~~~~~~~~~
                             withUnsafePointer to: 
Swift.withUnsafePointer:2:13: note: 'withUnsafePointer' has been explicitly marked unavailable here
public func withUnsafePointer<T, Result>(_ arg: inout T, _ body: (UnsafePointer<T>) throws -> Result) rethrows -> Result
            ^
/home/gery/projects/swifter/swifter/Sources/Socket+Server.swift:55:70: error: 'init' is unavailable: use 'withMemoryRebound(to:capacity:_)' to temporarily view memory as another layout-compatible type.
                    bind(socketFileDescriptor, UnsafePointer<sockaddr>($0), socklen_t(sizeof(sockaddr_in6)))
                                                                     ^
Swift.UnsafePointer<Pointee>:9:12: note: 'init' has been explicitly marked unavailable here
    public init?<U>(_ from: UnsafePointer<U>?)
           ^
/home/gery/projects/swifter/swifter/Sources/Socket+Server.swift:55:87: error: 'sizeof' is unavailable: use MemoryLayout<T>.size instead.
                    bind(socketFileDescriptor, UnsafePointer<sockaddr>($0), socklen_t(sizeof(sockaddr_in6)))
                                                                                      ^~~~~~~            ~
                                                                                      MemoryLayout<      >.size
/home/gery/projects/swifter/swifter/Sources/Socket.swift:102:35: error: use of undeclared type 'NSData'
    public func writeData(_ data: NSData) throws {
                                  ^~~~~~
/home/gery/projects/swifter/swifter/Sources/Socket.swift:106:35: error: use of undeclared type 'Data'
    public func writeData(_ data: Data) throws {
                                  ^~~~
/home/gery/projects/swifter/swifter/Sources/Socket.swift:174:13: error: instance member 'shutdown' cannot be used on type 'Socket'
            shutdown(socket, Int32(SHUT_RDWR))
            ^~~~~~~~
/home/gery/projects/swifter/swifter/Sources/Socket.swift:182:13: error: instance member 'shutdown' cannot be used on type 'Socket'
            shutdown(socket, Int32(SHUT_RDWR))
            ^~~~~~~~
/home/gery/projects/swifter/swifter/Sources/Socket.swift:102:35: error: use of undeclared type 'NSData'
    public func writeData(_ data: NSData) throws {
                                  ^~~~~~
/home/gery/projects/swifter/swifter/Sources/Socket.swift:106:35: error: use of undeclared type 'Data'
    public func writeData(_ data: Data) throws {
                                  ^~~~
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:23:24: error: use of undeclared type 'NSData'
    func write(_ data: NSData) throws
                       ^~~~~~
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:24:24: error: use of undeclared type 'Data'
    func write(_ data: Data) throws
                       ^~~~
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:23:24: error: use of undeclared type 'NSData'
    func write(_ data: NSData) throws
                       ^~~~~~
/home/gery/projects/swifter/swifter/Sources/HttpResponse.swift:24:24: error: use of undeclared type 'Data'
    func write(_ data: Data) throws
                       ^~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/gery/.swiftenv/versions/3.0/usr/bin/swift-build-tool -f /home/gery/projects/swifter/swifter/.build/debug.yaml

**Comment by glock45** [comment]
yep 👍 only mac is ready. It's still in progress.

**Comment by gery** [comment]
Ok thanks. 
I like this  project because no dependency hell like in other web frameworks.

**Comment by gery** [comment]
Now it compiles fine on linux, but do nothing when I start the server (with try also).
Do you have example server with error handling?

It Shows:
/home/gery/projects/swifter/swifter/Sources/main.swift:3:1: error: call can throw but is not marked with 'try'
server.start()
^~~~~~~~~~~~~~

**Comment by glock45** [comment]
Let's try this:
```
let server = HttpServer()

server["/test"] = { request in
        return .ok(.html("test"))
}
try server.start(9080, forceIPv4: true)

print("Server has started ( port = \(try server.port()) ). Try to connect now...")
while true { }
```

**Comment by gery** [comment]
Cool, its working now. 
Thanks a lot, Good job!
