### ISSUE TITLE
Carthage update fails with XCode 8 / Swift 2.3

### ISSUE THREAD

**Issue by Laban1** [httpswift/swifter#196]
After updating to XCode 8 and converting the project to Swift 2.3 I get this when attempting 
`carthage update --platform iOS`:

```
The following build commands failed:
    Check dependencies
(1 failure)
warning: no umbrella header found for target 'SwifteriOS', module map will not be generated
warning: no umbrella header found for target 'SwifteriOS', module map will not be generated
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Joe/Desktop/TheApp/Carthage/Checkouts/swifter/XCode/Swifter.xcodeproj -scheme SwifteriOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **
```

Advice on how to fix this would be great!

**Comment by git-no** [comment]
Maybe you want to consider migrating your project to Swift 3.

**Comment by Laban1** [comment]
That was the first thing I tried, but got the same issue.  I noticed that there were other issues reported with Swift 3 (Swifter does not appear to support Swift 3 yet), so I next tried with Swift 2.3 (expecting that at least this "legacy version" would work)...

**Comment by git-no** [comment]
Maybe you want to try it again. I had an simular situtation, but since yesterday, swifter supports XCode, Swift 3 (look into the commits). I was able to compile with Swift 3.

**Comment by marcoconti83** [comment]
I created a fork and restructure the folders so that carthage would not complain: https://github.com/marcoconti83/swifter . It fixed it for me.
