### ISSUE TITLE
Sharing static files not working (blank page)

### ISSUE THREAD

**Issue by git-no** [httpswift/swifter#197]
Why is it not possible to share static files like index.html?
I got everytime a blank page, empty response for response.
Used XCode 8, Swift 3, stable branch, download from today.

```
http://localhost:8080/index.html
```

Starting server like:
```
 private var webServer: HttpServer?

   do {
      let server = HttpServer()
      let publicDir = Bundle.main.bundlePath
      server["/shared/:path"] = shareFilesFromDirectory(publicDir)
      try server.start()
      webServer = server
   } catch {
      print("Server start error: \(error)")
   }
```

**Comment by glock45** [comment]
Should be fine now.

**Comment by git-no** [comment]
Thank you very much for the quick response, support and enhancement. Which you a nice weekend :-)
