### ISSUE TITLE
`Darwin.shutdown` doesn't actually close the socket

### ISSUE THREAD

**Issue by allen-zeng** [httpswift/swifter#201]
I'm writing a few iOS unit tests that rely on Swifter. The structure looks like the following:
```swift
class HttpClientTests: XCTestCase {
    private var server: HttpServer!

    override func setUp() {
        server = HttpServer()
    }

    override func tearDown() {
        server.stop()
    }

    func testA() {
        do {
             try server.start()
        } catch SocketError.bindFailed(let message) {
            XCTFail(message)
        } catch {
            XCTFail(error)
        }

        // rest of the test
    }

    // other tests that also begin with starting the server
}
```

The first test will always successfully start the Swifter server, however subsequent tests always fail with the error `SocketError.listenFailed("Address already in use")`.

I'm running Xcode 8 in macOS Sierra, running the Swift 3 compatible version at commit [d18f01](https://github.com/httpswift/swifter/tree/d18f0187970915c753d1dfc5cd94da5f8254c189) (latest at the time of writing).

The error is obviously thrown [here](https://github.com/httpswift/swifter/blob/d18f0187970915c753d1dfc5cd94da5f8254c189/Sources/Socket+Server.swift#L77). But what's more interesting is how it's shut down in the function [`release`](https://github.com/httpswift/swifter/blob/d18f0187970915c753d1dfc5cd94da5f8254c189/Sources/Socket.swift#L180): it consistently produces `-1`, which causes the following statement `close(socket)` to not be called.

Removing the `if` statement makes the tests pass, i.e. the server gets started and stopped correctly.

Having had a look at the documentation on [`shutdown`](http://www.manpages.info/macosx/shutdown.2.html), I looked into the actual error by printing `errno`, it consistently produces `57`, which according to [this page](https://www.freebsd.org/cgi/man.cgi?query=errno&sektion=2) maps to `ENOTCONN`. This value also exists in the macOS [`shutdown` man page](http://www.manpages.info/macosx/shutdown.2.html):
> The call succeeds unless:
...
[ENOTCONN]
The specified socket is not connected. 

I'm not entirely sure what the solution might be. Could somebody take a look?

Thanks in advance.

**Comment by glock45** [comment]
All shutdown calls should be removed and I am going to do this now.

**Comment by allen-zeng** [comment]
So I can see there is a 1.3.1 release. It doesn't seem to be on CocoaPods, will it be published soon?

**Comment by glock45** [comment]
I got a problem with pod spec lint. It's Swifter's podspec file or cocoapods does not support Swift 3.0.

**Comment by glock45** [comment]
I mange to solve the problem and 1.3.2 has landed on CocoaPods - https://github.com/CocoaPods/Specs/commit/9e7bc345340d51745829e6a679b3d1228433bc5d

**Comment by allen-zeng** [comment]
Works perfectly, thanks so much for getting onto it so quickly!
