### ISSUE TITLE
Can't install (just me?)

### ISSUE THREAD

**Issue by benicelabs** [httpswift/swifter#202]
Getting a "[!] Unable to find a specification for `Swifter (~> 1.2.6)`" error when trying a pod install. I'm new to CocoaPods, but it seems pretty straight forward. Should I be able to just install by dragging Sources?

**Comment by glock45** [comment]
Yep. Dragging the content of Source directory will work.

**Comment by glock45** [comment]
I did a release (1.3.1) to find out if cocoa-pods is ready for swift 3.0 but it's not.

**Comment by benicelabs** [comment]
Thanks. It was a silly issue on my machine.
