### ISSUE TITLE
Error with example in the README

### ISSUE THREAD

**Issue by benicelabs** [httpswift/swifter#203]
The example to start a server in the README states:
`server["/hello"] = { .OK(.Html("You asked for " + $0.url)) }`
However, this causes the error:
`Cannot assign value of type '(_) -> _' to type '((HttpRequest) -> HttpResponse)?`

**Comment by glock45** [comment]
@benicelabs thanks 👍  Let me know if this works for you (I've updated README):
> { .ok(.html("You asked for \($0)"))  }

**Comment by benicelabs** [comment]
This fixes the error in Xcode. However, when putting that code into viewDidLoad (for example) it give me an error because server.start() is marked as throw. So I try to wrap it in a do, try, catch. Like so...
`do {
         try server.start()
        } catch {
            print("nope")
        }`

**Comment by glock45** [comment]
Swift allows to omit arguments list and *in* keyword if you use Shorthand Argument Names (https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Closures.html#//apple_ref/doc/uid/TP40014097-CH11-ID94).

This should work:
`server["/turtles"] = { _ in .ok(.html("I like turtles.")) }`

**Comment by benicelabs** [comment]
Well duh on my part. I should have known that one. Thanks for the help.
