### ISSUE TITLE
DemoServer and routing "/"

### ISSUE THREAD

**Issue by tim-9red7** [httpswift/swifter#204]
I'm using the DemoServer as a template. Looking at this code below...
`server["/"] = scopes {
        html {
            body {
                ul(server.routes) { service in
                }
            }
        }
    }`

My problem:
If I remove the unordered list, the server is no longer reachable on any route. Any ideas?

**Comment by glock45** [comment]
Hello, 

Did you mange to solve this maybe ?

Best

**Comment by benicelabs** [comment]
Apologies. Just tried this again. Doesn't seem to be doing it any more.

**Comment by glock45** [comment]
No worries only dreams now :)
