### ISSUE TITLE
No accepted connection with 1.3.2 and Swift 3

### ISSUE THREAD

**Issue by maun** [httpswift/swifter#207]
I upgraded my application to Swift 3 and swifter 1.3.2, afterwards my request handlers were not called anymore when the location was accessed. I tried it on macOS and iOS using Carthage to install swifter.

Also the example from the Readme opens no ports for me.
In a blank Cocoa App created in Xcode 8:
```
    override func viewDidLoad() {
        super.viewDidLoad()

        let server = HttpServer()
        server["/hello"] = { .ok(.html("You asked for \($0)"))  }
        try! server.start(8001)
    }
```

I checked the open ports using `lsof -Pn -i4`, but no application listens on 8001.
I am using macOS Sierra 10.12.1 and the firewall is disabled, but my application also did not work on iOS 9.

Is there anything else I have to check?

**Comment by glock45** [comment]
It looks like the `server` variable is released after viewDidLoad's invocation.
Can you try to keep `server` variable as ViewController's property ? Here is an example: https://github.com/httpswift/swifter/blob/stable/XCode/SwifterSampleiOS/ViewController.swift

**Comment by maun** [comment]
Thank you, that was the problem. Should have found that myself but it worked for whatever reason with Swift 2.
