### ISSUE TITLE
Render HTML from httpserver in uiwebview?

### ISSUE THREAD

**Issue by charmander37** [httpswift/swifter#209]
Hi! 

I'm trying to take the html running on the swifter server and render it in a uiwebview - any idea how I can achieve this? I currently have the server starting and the webview setup, but I don't know how to connect the two :-( :

    var htmlFile = Bundle.main.path(forResource: "link", ofType: "html")
    var htmlString = try? String(contentsOfFile: htmlFile!, encoding: String.Encoding.utf8)
    
    let server = HttpServer()
    server["/my_html"] = scopes {
      htmlString
    }
    do {
      // 3
      try server.start()
      
      let webV:UIWebView = UIWebView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: self.view.frame.height))
      let url = Bundle.main.url(forResource: "link", withExtension: "html")
      webV.loadRequest(NSURLRequest(url: url!) as URLRequest)
      //webV.delegate = self;
      self.view.addSubview(webV)

    } catch is Error {
      //print(error)
    }

**Comment by glock45** [comment]
This should work for you: http://stackoverflow.com/a/26202983/351747

**Comment by charmander37** [comment]
Hi glock45! 

Thanks for getting back to me so quickly! That's what I'm doing down here:

  let webV:UIWebView = UIWebView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: self.view.frame.height))
  let url = Bundle.main.url(forResource: "link", withExtension: "html")
  webV.loadRequest(NSURLRequest(url: url!) as URLRequest)
  self.view.addSubview(webV)

In my example code. 

I'm asking how to user the local server to host the html and then render it in the webview. Does that make sense or am I totally crazy? Thanks again!

**Comment by charmander37** [comment]
If it helps - what I'm trying to do is the answer at the bottom of this question: http://stackoverflow.com/questions/11893153/uiwebview-html-file-with-swf-load-external-link-but-internal
