### ISSUE TITLE
CORS Help?

### ISSUE THREAD

**Issue by tim-9red7** [httpswift/swifter#210]
There is another CORS topic on here but it kind of died out. Is anyone able to give a newbie answer on how and where to add the correct header. Can I set this once for all headers?

**Comment by glock45** [comment]
hello,

CORS is not supported out of the box. This article should help: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by tim-9red7** [comment]
I'm familiar with CORS. My issue is that I'm not sure how to set the headers in Swifter. Is there an easy way to add "Access-Control-Allow-Origin: *" to my servers header using Swifter? Apologies if I'm being dense. I'm sure the answer is easier than it appears.

**Comment by glock45** [comment]
hello,

this should work for you.
```
server["/cors"] = { _ in
        return .raw(200, "OK", ["Access-Control-Allow-Origin": "*"], { writer in
            try? writer.write([UInt8]("hello".utf8))
        })
    }
```

**Comment by YiYiZheng** [comment]
```
server["/cors"] = { _ in
        return .raw(200, "OK", ["Access-Control-Allow-Origin": "*"], { writer in
            try? writer.write([UInt8]("hello".utf8))
        })
    }
```

It does not work in 1.4.6. Why? Thank you @glock45
