### ISSUE TITLE
Chinese will be garbled in queryParams

### ISSUE THREAD

**Issue by shalyf** [httpswift/swifter#212]
This method 'String.removePercentEncoding' will lead to garbled Chinese, it's normal by use 'String.removingPercentEncoding'

**Comment by glock45** [comment]
hello,

Do you think [this method ](https://developer.apple.com/reference/foundation/nsstring/1409569-stringbyremovingpercentencoding) will work for us ?

best

**Comment by shalyf** [comment]
I don't know. This is a temporary solution for me. I hope you can help me fix the issue, please!

**Comment by voynovia** [comment]
so it will work
https://github.com/httpswift/swifter/pull/215
