### ISSUE TITLE
MIME types?

### ISSUE THREAD

**Issue by pgaston** [httpswift/swifter#213]
Crazy thought - maybe I'm missing something obvious here, but wouldn't it be useful to put mime types into the http response?    
Files.swift - line 18 - the content type is always going to be text/html
Files.swift - line 26 - do a lookup for the content type based on the file extension?

One existing source is gitbub - MimeType.swift

Thanks!

**Comment by glock45** [comment]
You are right 👍

**Comment by pgaston** [comment]
Let's see if I can figure out how to suggest my change be merged - I've been a user, not a contributor in the past.    Seeing as it's in your 'demo server' function is should be safe.    Basically I simply integrated a lookup into a reasonable mime type list to get the content type.
