### ISSUE TITLE
Any way to bind to localhost such that the firewall isn't triggered?

### ISSUE THREAD

**Issue by brennantaylor** [httpswift/swifter#221]
Serving on `0.0.0.0` binds on all interfaces which trips the built in firewall since the computer is now accepting incoming connections. Binding to `127.0.0.1` or `localhost` should avoid this based on some searches.

Is there a way to expose the as an option? Even just exposing the address the server binds to?

**Comment by glock45** [comment]
Noted 👍

**Comment by nor-bu** [comment]
I'm not sure is this right, but when you set the public var `listenAddressIPv4` or the 'listenAddressIPv6' to `127.0.0.1` respective '::1' then i think is only listen to localhost.
@glock45 Is this right?

**Comment by brennantaylor** [comment]
From looking at the code that property appears to be internal and would not be available unless importing with `@testable`.

**Comment by brennantaylor** [comment]
Looks like this is addressed by https://github.com/httpswift/swifter/pull/222.

Closing.
