### ISSUE TITLE
Query items are not parsed correctly

### ISSUE THREAD

**Issue by BarakRL** [httpswift/swifter#225]
For example, this is a valid url:
`http://myserver/open?link=https://www.youtube.com/watch?v=D2cUBG4PnOA`

But with the current implementation of extractQueryParams, it will mess up the parameters due to the extra '?' and '=' marks.

However if you run it through:
```Swift
guard let urlComponents = URLComponents(string: url), let queryItems = urlComponents.queryItems else {
    return []
}

return queryItems.map { ($0.name, $0.value ?? "") }
```
You'll get the link parameter just fine.

**Comment by glock45** [comment]
Fixed at: 1.3.3.
