### ISSUE TITLE
Compilation hangs in Release config using Cocoapods

### ISSUE THREAD

**Issue by gravicle** [httpswift/swifter#233]
When using Cocoapods, building projects with Swifter in `Release` mode hangs. The compilation never finishes and there are 2 `swift` processes in Activity Monitor using 100% of the CPU indefinitely.  Tested in Xcode 8.3.2 and 8.3.1.

I was able to reproduce the issue in a fresh project ([TestSwifter.zip](https://github.com/httpswift/swifter/files/947657/TestSwifter.zip)):

1. Create new Xcode project
2. `pod init`
3. Add `Swifter` to podfile, 
4. Change the Build Configuration of scheme to `Release`
5. Build or Run

<img width="812" alt="screen shot 2017-04-21 at 9 22 43 am" src="https://cloud.githubusercontent.com/assets/1091114/25286899/35bdecc4-2674-11e7-8476-93bbaa2ed22e.png">

**Comment by glock45** [comment]
I can also reproduce this on my side. Quickly checked ` -Xfrontend -debug-time-function-bodies` flag but no output from there. It looks like the next step is to manully iterate over files and check which one is causing the problem.

**Comment by gravicle** [comment]
@glock45 how can I help?

**Comment by gh123man** [comment]
Hey guys, I ran into the same issue. Here is a temp workaround you can put in your podfile. 


```
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        if target.name == 'Swifter-iOS'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
            end
        end
    end
end
```

**Comment by florianheller** [comment]
I can confirm that building release-builds with optimization on Xcode 8 doesn't work (although I included Swifter manually into the Xcode project). Xcode 9-beta however, doesn't seem to have that problem.
