### ISSUE TITLE
Carthage build fails with error "Dependency "swifter" has no shared framework schemes for any of the platforms: iOS"

### ISSUE THREAD

**Issue by azizuysal** [httpswift/swifter#239]
Steps to repro, using Xcode 8.3.2, Carthage 0.22.0
1. Create a new Xcode project.
2. Create a Cartfile with contents "github "glock45/swifter""
3. In terminal run "carthage bootstrap --platform iOS"

Here's the output:
*** No Cartfile.resolved found, updating dependencies
*** Cloning swifter
*** Checking out swifter at "3.0.0"
*** xcodebuild output can be found in /var/folders/98/_0jlsbf94k36m_dhthm03mtm0000gn/T/carthage-xcodebuild.t4b3lT.log
*** Skipped building swifter due to the error:
Dependency "swifter" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/glock45/swifter/issues/new

**Comment by squeaky-nose** [comment]
Hi... did you manage to find a fix?

**Comment by marcoconti83** [comment]
I created a fork and restructure the folders so that carthage would not complain: https://github.com/marcoconti83/swifter
