### ISSUE TITLE
Rewrite for single page applications

### ISSUE THREAD

**Issue by bkawk** [httpswift/swifter#240]
The website I want to load into a webview is designed as a single page application, is there any way I can rewrite all url requests to index.html?

With nginx I'd do somthing like

server {
     listen 8080;
     listen [::] 8080;
     root /root/bundled;
 location / {
      try_files $uri $uri/ /index.html;
 }
}

How can this be done with swifter?

**Comment by oleander** [comment]
You could use `notFoundHandler`.

``` swift
 server.notFoundHandler = { request in
     return .ok(html("Not found :(")
   }
```

**Comment by michaelenger** [comment]
The feature added in #479 would allow you to do this:

```swift
server["/**"] = { request in
    return .ok(.htmlBody("You're at: \(request.path)"))
}
```

However, this won't match `/` directly, so a separate handler needs to be added for that:

```swift
server["/"] = { request in
    return .ok(.htmlBody("You got the root!"))
}
```
