### ISSUE TITLE
Xcode warnings

### ISSUE THREAD

**Issue by matsoftware** [httpswift/swifter#241]
The current stable version of the library produces 7 warnings in Xcode 8.3.2:

<img width="423" alt="screen shot 2017-05-18 at 11 20 31" src="https://cloud.githubusercontent.com/assets/1196694/26198039/6bf998e4-3bbc-11e7-8a25-ef2633d40676.png">

Is there any plan to fix them?
Cheers

**Comment by voynovia** [comment]
I created a PR https://github.com/httpswift/swifter/pull/250
