### ISSUE TITLE
Files cannot be accessed by shareFilesFromDirectory method

### ISSUE THREAD

**Issue by hipposan** [httpswift/swifter#246]
The code is
 `server["/"] = shareFilesFromDirectory(MyPath)
   server.start(8080)
`
Then open browser and type "http://127.0.0.1", nothing happened?

**Comment by SmileAppDev** [comment]
Did you try http:127.0.0.1:8080 ? or localhost:8080.

**Comment by hipposan** [comment]
@SmileAppDev Yes, I tried.

**Comment by dntbrsnbl** [comment]
Did you include the port number in the address?
Were you connecting from the same machine that you were running the code on? 
If it was on iOS, was the app in the foreground when you attempted to connect?
