### ISSUE TITLE
Help me.. 

### ISSUE THREAD

**Issue by starqueen106** [httpswift/swifter#257]
Now i create the 2 method for M3u8 and TS
but dont load the TS file.

public func shareFileForM3u8(_ path: String) -> ((HttpRequest) -> HttpResponse) {
    return { r in
        // application/octet-stream
        if let file = try? path.openForReading() {
            return .raw(200, "OK", ["Content-Type":"application/vnd.apple.mpegurl"], { writer in
                try? writer.write(file)
                file.close()
            })
        }
        return .notFound
    }
}

public func shareFileForTS(_ path: String) -> ((HttpRequest) -> HttpResponse) {
    return { r in
        if let file = try? path.openForReading() {
            return .raw(200, "OK", [:], { writer in
                try? writer.write(file)
                file.close()
            })
        }
        return .notFound
    }
}

what is missing?
how to play the ts file on local ?
of course  , i started the local HttpServer ( http://127.0.0.1:8080)
Please help me..
thanks

**Comment by pvegh** [comment]
You might get more help if you actually describe your problem and use an appropriate title.
