### ISSUE TITLE
Fails to compile with Xcode9 beta5 due to breaking (maybe non-intentional) swift changes

### ISSUE THREAD

**Issue by delebedev** [httpswift/swifter#259]
https://bugs.swift.org/browse/SR-5659

<img width="1085" alt="screen shot 2017-08-08 at 09 34 31" src="https://user-images.githubusercontent.com/829783/29063213-cfc2470e-7c1c-11e7-9824-851e33a2da4d.png">

**Comment by kwridan** [comment]
Latest stable branch works fine on Xcode 9 beta 5. The referenced method in the screenshot has been removed in favour of the built method. 

https://github.com/httpswift/swifter/commit/82894dcfd5dfe457c62acc37d3bad54335986181#diff-aee1a2c4ba050f381dd3663379855341

I originally encountered the same issue then realised I hadn't updated my local copy in a while :)
