### ISSUE TITLE
'No such module as Swifter' error

### ISSUE THREAD

**Issue by DDBRemedyUK** [httpswift/swifter#267]
Hi,

Whenever I install using Cocoa Pods and open the project from the workspace, I get error 
`No such module 'Swifter'`

I get this error even after I clean and build the project.

Any ideas? Im running in Xcode 9 (stable) with Swift 4.

**Comment by johnnyvj** [comment]
Hello!

I have this problema too, and I don't know what is the problem.

I'm using too xCode 9 and Swift 4.

Please, help us, if possible!

**Comment by johnnyvj** [comment]
So, I with many friends here in the net solved the problem finally: in xCode set the SWIFTER_VERSION to 3.2 and it working! Thanks!

**Comment by srijanraj** [comment]
How can I change SWIFTER_VERSION in xCode? @johnnyvj

**Comment by johnnyvj** [comment]
So, open your project in xCode. On left side in navigator click to your project's name. In the middle panel find Build Setting. Here you use the top-right section you see the search bar. Write to SWIFT_VERSION and you will se the Swift Language Version line above. Here change to Swift 3.2 and done.

**Comment by srijanraj** [comment]
Thanks @johnnyvj , It worked. Hey I am new to swift and trying to mock the server for ui test using Swifter. Do you have any relevant resource which can help me.
