### ISSUE TITLE
bind operation not permitted

### ISSUE THREAD

**Issue by nicholascross** [httpswift/swifter#292]
I just ran in to a problem trying to embed the http server into a macos application.

It would fail to bind on any ip address the solution was not straight forward to locate for someone not experienced with such things, so I thought I would share it here in case others face it in the future.

To resolve you must update your apps entitlements file with the following

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.app-sandbox</key>
    <false/>
    <key>com.apple.security.files.user-selected.read-only</key>
    <false/>
</dict>
</plist>
```

These will be true by default.

I found the solution [here](https://stackoverflow.com/a/48224925/5133868)

If there are any better solutions please share!

**Comment by jeff-h** [comment]
Thanks for this!

Also in a macOS app, the error I was getting was: `bindFailed("Operation not permitted")` and the fix was simply to tick "Incoming Connections" in the App Sandbox config.

<img width="552" alt="screen shot 2018-02-19 at 9 14 00 pm" src="https://user-images.githubusercontent.com/841871/36367957-e5f540f8-15b9-11e8-8b15-3f61c6df9496.png">

Absolutely obvious after you think of it!

**Comment by nicholascross** [comment]
This does seem like the correct way to get things working, as it leaves the other sandbox entitlements untouched!

The entitlements below work correctly, thanks for sharing this info!

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.files.user-selected.read-only</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
</dict>
</plist>
```
