### ISSUE TITLE
Bind Error : Address already in use

### ISSUE THREAD

**Issue by shiva28U** [httpswift/swifter#306]
Im using swifter with uitest iOS for mocking web response. It works fine when normal test but in continues integration with parallel execution using multiple simulator creates this "**Address already in use**" error in crash log with localhost server.

Can anyone help me out reg this!!!

**Comment by Vkt0r** [comment]
You can specify the `port` you want to use to run the server. So you need a way to identify each instance if you're running your tests in the same simulator instance or in different simulators and specify different ports for each one.

**Comment by Vkt0r** [comment]
@shiva28U This is something that can work if you have paralleling testing for example.

```swift
/// Start the HTTP server in the specified port number, in case of the port number
/// is being used it would try to find another free port.
///
/// - Parameters:
///   - port: The port number to start the server
///   - maximumOfAttempts: The maximum number of attempts to find an unused port
private func startServer(port: in_port_t = 8080, maximumOfAttempts: Int = 5) {
        
   // Stop the retrying when the attempts is zero
   if maximumOfAttempts == 0 {
      return
   }
        
   do {
      try server.start(port)
      print("Server has started ( port = \(try server.port()) ). Try to connect now...")
   } catch SocketError.bindFailed(let message) where message == "Address already in use" {
        startServer(port: in_port_t.random(in: 8081..<10000), maximumOfAttempts: maximumOfAttempts - 1)
   } catch {
       print("Server start error: \(error)")
   }        
}
```

The above code is something I been testing for paralleling testing and I only set ports between `8081..<10000` that's something can be extended to any other range. Note if you have any other error you need to handle it properly.
