### ISSUE TITLE
1.4.0 compile error

### ISSUE THREAD

**Issue by kimaldis** [httpswift/swifter#308]
I'm getting a compile error, Line 47 of Webserver.swift,

      "Type 'String' has no member 'fromUInt8'"

Xcode 9.3, Swift 4.1

**Comment by benchd** [comment]
At the moment I don't think this is going to work. See issue #302 as the pod hasn't been updated to support swift 4.1.

**Comment by kimaldis** [comment]
This was with the source folder dragged into the Xcode project. Only because last time I looked at this code I couldn't get it to build with it in the podfile.
